"""One-time, non-destructive migration of local SQLite authentication users to PostgreSQL."""

import os
import sqlite3
import sys
from pathlib import Path

import psycopg


BASE_DIR = Path(__file__).resolve().parent
SQLITE_PATH = BASE_DIR / "auth_users.sqlite3"
POSTGRES_URL = os.getenv("AUTH_DATABASE_URL", "").strip()

POSTGRES_USERS_SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL CHECK(role IN ('admin', 'doctor')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    name TEXT,
    hospital TEXT,
    specialization TEXT
)
"""


def main() -> int:
    if not POSTGRES_URL:
        print("AUTH_DATABASE_URL must be set before migration.", file=sys.stderr)
        return 2
    if not SQLITE_PATH.exists():
        print("Local SQLite authentication database was not found.", file=sys.stderr)
        return 2

    sqlite_uri = f"file:{SQLITE_PATH.as_posix()}?mode=ro"
    with sqlite3.connect(sqlite_uri, uri=True) as sqlite_conn:
        sqlite_conn.row_factory = sqlite3.Row
        users = sqlite_conn.execute(
            "SELECT id, email, password_hash, role, created_at, is_active, name, hospital, specialization FROM users ORDER BY id"
        ).fetchall()

    with psycopg.connect(POSTGRES_URL) as postgres_conn:
        with postgres_conn.cursor() as cursor:
            cursor.execute(POSTGRES_USERS_SCHEMA)
            cursor.execute("SELECT COUNT(*) FROM users")
            if cursor.fetchone()[0] != 0:
                print("PostgreSQL users table is not empty; no users were migrated.", file=sys.stderr)
                return 3

            for user in users:
                cursor.execute(
                    """
                    INSERT INTO users (id, email, password_hash, role, created_at, is_active, name, hospital, specialization)
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
                    """,
                    (
                        user["id"], user["email"], user["password_hash"], user["role"], user["created_at"],
                        bool(user["is_active"]), user["name"], user["hospital"], user["specialization"],
                    ),
                )
            if users:
                cursor.execute(
                    "SELECT setval(pg_get_serial_sequence('users', 'id'), %s, true)",
                    (users[-1]["id"],),
                )

    print(f"Migrated {len(users)} authentication users to PostgreSQL.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
